export type {
  XmlAttribute,
  XmlBudgetExceededDetails,
  XmlDocument,
  XmlElementNode,
  XmlNode,
  XmlNodeKind,
  XmlParseBudgets,
  XmlReplayContract,
  XmlReplayEvent,
  XmlReplayInput,
  XmlReplayOptions,
  XmlReplayVerificationResult,
  XmlParseError,
  XmlParseOptions,
  XmlSpan,
  XmlTextNode,
  XmlToken,
  XmlTokenAttribute
} from "../internal/types.js";
